---
version: '3'

services:
  developer-tools:
    image: entechlog/developer-tools${DEVELOPER_TOOLS_VERSION_TAG}
    container_name: developer-tools
    build: ./docker/
    command: 
      - bash 
      - -c 
      - |
        echo "Launching developer-tools"
        sleep infinity
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - type: bind
        source: /C
        target: /C
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      - TZ=Etc/GMT
      - SAM_CLI_TELEMETRY=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
